# Accessing Data within Pandas - Lab

## Introduction

In this lab, we'll look at a dataset which contains information on World Cup matches. Let's use the pandas commands learned in the previous lesson to learn more about our data!

## Objectives

You will be able to: 

- Use pandas methods and attributes to access information about a dataset 
- Index pandas dataframes with .loc, .iloc, and column names 
- Use a boolean mask to index pandas series and dataframes

## Load the Data

Load the file `'WorldCupMatches.csv'` as a DataFrame in pandas.

In [1]:
# Replace None with appropriate code

# Import pandas using the standard alias
import pandas as pd 

# Load 'WorldCupMatches.csv' as a DataFrame
df = pd.read_csv("WorldCupMatches.csv")

## Common Methods and Attributes

Use the correct method to display the **first 7 rows** of the dataset.

In [4]:
# Your code here
df.head(7)

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444.0,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX
1,1930,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,,18346.0,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL
2,1930,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059.0,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409.0,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA
5,1930,16 Jul 1930 - 14:45,Group 1,Parque Central,Montevideo,Chile,3,0,Mexico,,9249.0,1,0,CRISTOPHE Henry (BEL),APHESTEGUY Martin (URU),LANGENUS Jean (BEL),201,1095,CHI,MEX
6,1930,17 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,4,0,Bolivia,,18306.0,0,0,MATEUCCI Francisco (URU),LOMBARDI Domingo (URU),WARNKEN Alberto (CHI),201,1092,YUG,BOL

Display the **last 3 rows** of the dataset.

In [6]:
# Your code here
df.tail(3)

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
849,2014,09 Jul 2014 - 17:00,Semi-finals,Arena de Sao Paulo,Sao Paulo,Netherlands,0,0,Argentina,Argentina win on penalties (2 - 4),63267.0,0,0,C�neyt �AKIR (TUR),DURAN Bahattin (TUR),ONGUN Tarik (TUR),255955,300186490,NED,ARG
850,2014,12 Jul 2014 - 17:00,Play-off for third place,Estadio Nacional,Brasilia,Brazil,0,3,Netherlands,,68034.0,0,2,HAIMOUDI Djamel (ALG),ACHIK Redouane (MAR),ETCHIALI Abdelhak (ALG),255957,300186502,BRA,NED
851,2014,13 Jul 2014 - 16:00,Final,Estadio do Maracana,Rio De Janeiro,Germany,1,0,Argentina,Germany win after extra time,74738.0,0,0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255959,300186501,GER,ARG

Get a concise summary of the data using `.info()`.

In [8]:
# Your code here
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 852 entries, 0 to 851
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  852 non-null    int64
 1   Datetime              852 non-null    object
 2   Stage                 852 non-null    object
 3   Stadium               852 non-null    object
 4   City                  852 non-null    object
 5   Home Team Name        852 non-null    object
 6   Home Team Goals       852 non-null    int64
 7   Away Team Goals       852 non-null    int64
 8   Away Team Name        852 non-null    object
 9   Win conditions        852 non-null    object
 10  Attendance            850 non-null    float64
 11  Half-time Home Goals  852 non-null    int64
 12  Half-time Away Goals  852 non-null    int64
 13  Referee               852 non-null    object
 14  Assistant 1           852 non-null    object
 15  Assistant 2           852 non-null    object
 16  RoundID               852 non-null    int64
 17  MatchID               852 non-null    int64
 18  Home Team Initials    852 non-null    object
 19  Away Team Initials    852 non-null    object
dtypes: float64(1), int64(7), object(12)
memory usage: 133.3+ KB

Obtain a tuple representing the **number of rows and number of columns**.

In [10]:
# Your code here
df.shape

(852, 20)

Use the appropriate attribute to get the **column names**.

In [17]:
# Your code here
df.columns

Index(['Year', 'Datetime', 'Stage', 'Stadium', 'City', 'Home Team Name',
       'Home Team Goals', 'Away Team Goals', 'Away Team Name',
       'Win conditions', 'Attendance', 'Half-time Home Goals',
       'Half-time Away Goals', 'Referee', 'Assistant 1', 'Assistant 2',
       'RoundID', 'MatchID', 'Home Team Initials', 'Away Team Initials'],
      dtype='object')

## Selecting DataFrame Information

When looking at the DataFrame's `.head()` and `.tail()`, you might have noticed that the games are structured chronologically in the DataFrame.

Use the right selection method to display all the information from the 3rd to the 5th game (i.e. **select rows 3 through 5 inclusive**).

In [21]:
# Your code here
df.iloc[3:6]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409.0,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA
5,1930,16 Jul 1930 - 14:45,Group 1,Parque Central,Montevideo,Chile,3,0,Mexico,,9249.0,1,0,CRISTOPHE Henry (BEL),APHESTEGUY Martin (URU),LANGENUS Jean (BEL),201,1095,CHI,MEX

Now, display the info from **game 5-9** (inclusive), but **only the `"Home Team Name"` and the `"Away Team Name"` columns**.

In [24]:
# Your code here
df.iloc[5:10,[5,8]]

  Home Team Name Away Team Name
5          Chile         Mexico
6     Yugoslavia        Bolivia
7            USA       Paraguay
8        Uruguay           Peru
9          Chile         France

Next, we'd like the information on all the games played in **Group 3** for the **1950** World Cup.

Hint: You can combine conditions like this:

`df[(condition1) | (condition2)]`  -> Returns rows where either condition is true

`df[(condition1) & (condition2)]`  -> Returns rows where both conditions are true

In [28]:
# Your code here
df.loc[df['Year'] == 1950]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
53,1950,24 Jun 1950 - 15:00,Group 1,Maracan� - Est�dio Jornalista M�rio Filho,Rio De Janeiro,Brazil,4,0,Mexico,,81649.0,1,0,READER George (ENG),GRIFFITHS Benjamin (WAL),MITCHELL George (SCO),208,1187,BRA,MEX
54,1950,25 Jun 1950 - 15:00,Group 2,Maracan� - Est�dio Jornalista M�rio Filho,Rio De Janeiro,England,2,0,Chile,,29703.0,1,0,VAN DER MEER Karel (NED),GARDELLI Mario (BRA),DAHLNER Gunnar (SWE),208,1192,ENG,CHI
55,1950,25 Jun 1950 - 15:00,Group 2,Durival de Brito,Curitiba,Spain,3,1,USA,,9511.0,0,1,VIANA Mario (BRA),DA COSTA VIEIRA Jose (POR),DE LA SALLE Charles (FRA),208,1208,ESP,USA
56,1950,25 Jun 1950 - 15:00,Group 3,Pacaembu,Sao Paulo,Sweden,3,2,Italy,,36502.0,2,1,LUTZ Jean (SUI),BERANEK Alois (AUT),TEJADA Carlos (MEX),208,1219,SWE,ITA
57,1950,25 Jun 1950 - 15:00,Group 1,Independencia,Belo Horizonte,Yugoslavia,3,0,Switzerland,,7336.0,0,0,GALEATI Giovanni (ITA),EKLIND Ivan (SWE),DATTILO Generoso (ITA),208,1230,YUG,SUI
58,1950,28 Jun 1950 - 15:00,Group 1,Pacaembu,Sao Paulo,Brazil,2,2,Switzerland,,42032.0,2,1,AZON ROMA Ramon (ESP),BUSTAMANTE Sergio (CHI),DE NICOLA Cayetano (PAR),208,1188,BRA,SUI
59,1950,28 Jun 1950 - 15:00,Group 1,Eucaliptos,Porto Alegre,Yugoslavia,4,1,Mexico,,11078.0,2,0,LEAFE Reginald (ENG),DAHLNER Gunnar (SWE),VAN DER MEER Karel (NED),208,1225,YUG,MEX
60,1950,29 Jun 1950 - 15:00,Group 2,Maracan� - Est�dio Jornalista M�rio Filho,Rio De Janeiro,Spain,2,0,Chile,,19790.0,2,0,MALCHER Alberto (BRA),MARINO Esteban (URU),ALVAREZ Alfredo (BOL),208,1193,ESP,CHI
61,1950,29 Jun 1950 - 15:30,Group 3,Durival de Brito,Curitiba,Sweden,2,2,Paraguay,,7903.0,2,1,MITCHELL Robert (SCO),LEMESIC Leo (YUG),GARCIA Prudencio (USA),208,1228,SWE,PAR
62,1950,29 Jun 1950 - 15:00,Group 2,Independencia,Belo Horizonte,USA,1,0,England,,10151.0,1,0,DATTILO Generoso (ITA),DE LA SALLE Charles (FRA),GALEATI Giovanni (ITA),208,1202,USA,ENG
63,1950,01 Jul 1950 - 15:00,Group 1,Maracan� - Est�dio Jornalista M�rio Filho,Rio De Janeiro,Brazil,2,0,Yugoslavia,,142429.0,1,0,GRIFFITHS Benjamin (WAL),BERANEK Alois (AUT),DA COSTA VIEIRA Jose (POR),208,1191,BRA,YUG
64,1950,02 Jul 1950 - 15:00,Group 2,Maracan� - Est�dio Jornalista M�rio Filho,Rio De Janeiro,Spain,1,0,England,,74462.0,0,0,GALEATI Giovanni (ITA),LUTZ Jean (SUI),DATTILO Generoso (ITA),208,1199,ESP,ENG
65,1950,02 Jul 1950 - 15:00,Group 3,Pacaembu,Sao Paulo,Italy,2,0,Paraguay,,25811.0,1,0,ELLIS Arthur (ENG),GARCIA Prudencio (USA),DE LA SALLE Charles (FRA),208,1218,ITA,PAR
66,1950,02 Jul 1950 - 15:00,Group 4,Independencia,Belo Horizonte,Uruguay,8,0,Bolivia,,5284.0,4,0,READER George (ENG),VIANA Mario (BRA),LEMESIC Leo (YUG),208,1185,URU,BOL
67,1950,02 Jul 1950 - 15:40,Group 1,Eucaliptos,Porto Alegre,Switzerland,2,1,Mexico,,3580.0,2,0,EKLIND Ivan (SWE),DAHLNER Gunnar (SWE),BUSTAMANTE Sergio (CHI),208,1222,SUI,MEX
68,1950,02 Jul 1950 - 15:00,Group 2,Ilha do Retiro,Recife,Chile,5,2,USA,,8501.0,2,0,GARDELLI Mario (BRA),HEYEN Mario Ruben (PAR),ALVAREZ Alfredo (BOL),208,1194,CHI,USA
69,1950,09 Jul 1950 - 15:00,Group 6,Pacaembu,Sao Paulo,Uruguay,2,2,Spain,,44802.0,1,2,GRIFFITHS Benjamin (WAL),DATTILO Generoso (ITA),ALVAREZ Alfredo (BOL),209,1207,URU,ESP
70,1950,09 Jul 1950 - 15:00,Group 6,Maracan� - Est�dio Jornalista M�rio Filho,Rio De Janeiro,Brazil,7,1,Sweden,,138886.0,3,0,ELLIS Arthur (ENG),GARCIA Prudencio (USA),DE LA SALLE Charles (FRA),209,1189,BRA,SWE
71,1950,13 Jul 1950 - 15:00,Group 6,Maracan� - Est�dio Jornalista M�rio Filho,Rio De Janeiro,Brazil,6,1,Spain,,152772.0,3,0,LEAFE Reginald (ENG),MITCHELL George (SCO),DA COSTA VIEIRA Jose (POR),209,1186,BRA,ESP
72,1950,13 Jul 1950 - 15:00,Group 6,Pacaembu,Sao Paulo,Uruguay,3,2,Sweden,,7987.0,1,2,GALEATI Giovanni (ITA),BERANEK Alois (AUT),DE NICOLA Cayetano (PAR),209,1231,URU,SWE
73,1950,16 Jul 1950 - 15:00,Group 6,Pacaembu,Sao Paulo,Sweden,3,1,Spain,,11227.0,2,0,VAN DER MEER Karel (NED),LUTZ Jean (SUI),GARCIA Prudencio (USA),209,1206,SWE,ESP
74,1950,16 Jul 1950 - 15:00,Group 6,Maracan� - Est�dio Jornalista M�rio Filho,Rio De Janeiro,Uruguay,2,1,Brazil,,173850.0,0,0,READER George (ENG),ELLIS Arthur (ENG),MITCHELL George (SCO),209,1190,URU,BRA

Let's repeat the command above, but this time display **only the attendance column** for the Group 3 games.

In [31]:
# Your code here
df.loc[df['Year'] == 1950, 'Attendance']

53     81649.0
54     29703.0
55      9511.0
56     36502.0
57      7336.0
58     42032.0
59     11078.0
60     19790.0
61      7903.0
62     10151.0
63    142429.0
64     74462.0
65     25811.0
66      5284.0
67      3580.0
68      8501.0
69     44802.0
70    138886.0
71    152772.0
72      7987.0
73     11227.0
74    173850.0
Name: Attendance, dtype: float64

Throughout the entire history of the World Cup as recorded in this dataset, **how many home games were played by the Netherlands**?

(Remember that you can use the `len()` built-in function to find the number of rows in a DataFrame.)

In [34]:
# Your code here
len(df.loc[(df['Home Team Name'] == 'Netherlands')])

32

**How many games were played by the Netherlands in total**?

In [37]:
# Your code here
len(df.loc[(df['Home Team Name'] == 'Netherlands') | (df['Away Team Name'] == 'Netherlands')])

54

Next, let's try and figure out **how many games the USA played in the 2014 World Cup**.

In [40]:
# Your code here
len(df.loc[(df['Year'] == 2014) & ((df['Home Team Name'] == 'USA') | (df['Away Team Name'] == 'USA'))])

5

Now, let's try to find out **how many countries participated in the 1986 World Cup**.

Hint 1: As a first step, create a new dataset that only contains games in that year.

Hint 2: Make sure you don't end up with duplicate country names. Consider using `set()` or `.unique()`.

In [44]:
# Your code here
df_sub = df.loc[df['Year'] == 1986]
countries = df["Home Team Name"].unique()
set(countries)

{'Algeria',
 'Angola',
 'Argentina',
 'Australia',
 'Austria',
 'Belgium',
 'Bolivia',
 'Brazil',
 'Bulgaria',
 'Cameroon',
 'Canada',
 'Chile',
 'China PR',
 'Colombia',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Czech Republic',
 'Czechoslovakia',
 "C�te d'Ivoire",
 'Denmark',
 'Ecuador',
 'England',
 'France',
 'German DR',
 'Germany',
 'Germany FR',
 'Ghana',
 'Greece',
 'Haiti',
 'Honduras',
 'Hungary',
 'IR Iran',
 'Iran',
 'Iraq',
 'Italy',
 'Jamaica',
 'Japan',
 'Korea DPR',
 'Korea Republic',
 'Mexico',
 'Morocco',
 'Netherlands',
 'New Zealand',
 'Nigeria',
 'Northern Ireland',
 'Norway',
 'Paraguay',
 'Peru',
 'Poland',
 'Portugal',
 'Romania',
 'Russia',
 'Saudi Arabia',
 'Scotland',
 'Senegal',
 'Serbia',
 'Slovakia',
 'Slovenia',
 'South Africa',
 'Soviet Union',
 'Spain',
 'Sweden',
 'Switzerland',
 'Togo',
 'Tunisia',
 'Turkey',
 'USA',
 'Ukraine',
 'Uruguay',
 'Wales',
 'Yugoslavia',
 'Zaire',
 'rn">Bosnia and Herzegovina',
 'rn">Republic of Ireland',
 'rn">Serbia and Montenegro',
 'rn">Trinidad and Tobago',
 'rn">United Arab Emirates'}

## Changing Values and Creating New Columns

In World Cup history, **how many matches had 5 goals or more in total**? Create a column `"Total Goals"` to answer this question.

In [48]:
# Your code here
df['Total Goals'] = df['Home Team Goals'] + df['Away Team Goals']
len(df.loc[df['Total Goals'] >= 5])

147

Now **create a new column `"Half-time Goals"`** in `df` that includes both home and away values.

In [51]:
# Your code here
df['Half-time Goals'] = df['Half-time Home Goals'] + df['Half-time Away Goals']
df.head()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,...,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials,Total Goals,Half-time Goals
0,1930,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,...,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX,5,3
1,1930,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,,...,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL,3,2
2,1930,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,...,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA,3,2
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,...,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER,4,1
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,...,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA,1,0

In [53]:
# Run this cell without changes to see your new column
df.columns

Index(['Year', 'Datetime', 'Stage', 'Stadium', 'City', 'Home Team Name',
       'Home Team Goals', 'Away Team Goals', 'Away Team Name',
       'Win conditions', 'Attendance', 'Half-time Home Goals',
       'Half-time Away Goals', 'Referee', 'Assistant 1', 'Assistant 2',
       'RoundID', 'MatchID', 'Home Team Initials', 'Away Team Initials',
       'Total Goals', 'Half-time Goals'],
      dtype='object')

Run the code below. You'll notice that for Korea, there are records for both North-Korea (Korea DPR) and South-Korea (Korea Republic).

In [56]:
# Run this cell without changes

# Display all records containing the string 'Korea'
df.loc[df['Home Team Name'].str.contains('Korea'), 'Home Team Name']

179         Korea DPR
187         Korea DPR
374    Korea Republic
386    Korea Republic
434    Korea Republic
444    Korea Republic
480    Korea Republic
524    Korea Republic
593    Korea Republic
609    Korea Republic
635    Korea Republic
642    Korea Republic
655    Korea Republic
710    Korea Republic
753         Korea DPR
802    Korea Republic
818    Korea Republic
Name: Home Team Name, dtype: object

Imagine that, for some reason, we simply want Korea listed as one entry, so we want to replace every "Home Team Name" and "Away Team Name" entry that contains "Korea" to simply "Korea". In the same way, we want to change the columns "Home Team Initials" and "Away Team Initials" to NSK (North & South Korea) instead of "KOR" and "PRK".

In [68]:
# Update the 'Home Team Name' and 'Home Team Initials' columns 
df.loc[df['Home Team Name'].str.contains('Korea'), 'Home Team Name'] = 'Korea'
df.loc[df['Away Team Name'].str.contains('Korea'), 'Away Team Name'] = 'Korea'
df.loc[df['Home Team Initials'].str.contains('KOR', 'PRK'), 'Home Team Initials'] = 'NSK'
df.loc[df['Away Team Initials'].str.contains('KOR', 'PRK'), 'Away Team Initials'] = 'NSK'

Make sure to verify your answer!

In [70]:
# Check the updated columns
df.loc[df['Home Team Initials'] == 'NSK']

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,...,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials,Total Goals,Half-time Goals
374,1986,05 Jun 1986 - 16:00,Group A,Estadio Ol�mpico Universitario,Mexico City,Korea,1,1,Bulgaria,,...,1,AL SHANAR Fallaj Khuzam (KSA),IGNA Ioan (ROU),BUTENKO Valeri (RUS),308,460,NSK,BUL,2,1
386,1986,10 Jun 1986 - 12:00,Group A,Cuauhtemoc,Puebla,Korea,2,3,Italy,,...,1,SOCHA David (USA),URREA Joaquin (MEX),AL SHARIF Jamal (SYR),308,643,NSK,ITA,5,1
434,1990,17 Jun 1990 - 21:00,Group E,Dacia Arena,Udine,Korea,1,3,Spain,,...,1,JACOME GUERRERO Elias V. (ECU),MAGNI Pierluigi (ITA),LOUSTAU Juan (ARG),322,175,NSK,ESP,4,2
444,1990,21 Jun 1990 - 17:00,Group E,Friuli,Udine,Korea,0,1,Uruguay,,...,0,LANESE Tullio (ITA),DIRAMBA Jean Fidele (GAB),JOUINI Neji (TUN),322,290,NSK,URU,1,0
480,1994,23 Jun 1994 - 19:30,Group C,Foxboro Stadium,Boston,Korea,0,0,Bolivia,,...,0,MOTTRAM Leslie (SCO),MATTHYS Luc (BEL),EVERSTIG Mikael (SWE),337,3065,NSK,BOL,0,0
524,1998,13 Jun 1998 - 17:30,Group E,Stade de Gerland,Lyon,Korea,1,3,Mexico,,...,0,BENKO Gunter (AUT),FRED Lencie (VAN),SCHNEIDER Erich (GER),1014,8732,NSK,MEX,4,1
593,2002,04 Jun 2002 - 20:30,Group D,Busan Asiad Main Stadium,Busan,Korea,2,0,Poland,,...,0,RUIZ Oscar (COL),DORIRI Elise (VAN),LINDBERG Leif (SWE),43950100,43950014,NSK,POL,2,1
609,2002,10 Jun 2002 - 15:30,Group D,Daegu World Cup Stadium,Daegu,Korea,1,1,USA,,...,1,MEIER Urs (SUI),BEREUTER Egon (AUT),TOMUSANGE Ali (UGA),43950100,43950030,NSK,USA,2,1
635,2002,18 Jun 2002 - 20:30,Round of 16,Daejeon World Cup Stadium,Daejeon,Korea,2,1,Italy,Win on Golden Goal,...,0,MORENO Byron (ECU),RATTALINO Jorge (ARG),SZEKELY Ferenc (HUN),43950200,43950056,NSK,ITA,3,0
642,2002,29 Jun 2002 - 20:00,Third place,Daegu World Cup Stadium,Daegu,Korea,2,3,Turkey,,...,3,MANE Saad (KUW),ALTRAIFI Ali (KSA),VERGARA Hector (CAN),43950500,43950063,NSK,TUR,5,4
655,2006,13 Jun 2006 - 15:00,Group G,"FIFA World Cup Stadium, Frankfurt",Frankfurt/Main,Korea,2,1,Togo,,...,1,POLL Graham (ENG),SHARP Philip (ENG),TURNER Glenn (ENG),97410100,97410014,NSK,TOG,3,1
710,2010,12 Jun 2010 - 13:30,Group B,Port Elizabeth Stadium,Nelson Mandela Bay/Port Elizabeth,Korea,2,0,Greece,,...,0,HESTER Michael (NZL),HINTZ Jan Hendrik (NZL),MAKASINI Tevita (TGA),249722,300061459,NSK,GRE,2,1
802,2014,22 Jun 2014 - 16:00,Group H,Estadio Beira-Rio,Porto Alegre,Korea,2,4,Algeria,,...,3,ROLDAN Wilmar (COL),DIAZ Eduardo (COL),LESCANO Christian (ECU),255931,300186495,NSK,ALG,6,3
818,2014,26 Jun 2014 - 17:00,Group H,Arena de Sao Paulo,Sao Paulo,Korea,0,1,Belgium,,...,0,Ben WILLIAMS (AUS),CREAM Matthew (AUS),ANAZ Hakan (AUS),255931,300186480,NSK,BEL,1,0

## Summary

In this lab, you practiced accessing data within Pandas!